### ISSUE TITLE
Consolidate Configuration to Rulesets

### ISSUE THREAD

**Issue by jack-avery** [jack-avery/ansible-tf2network#20]
Allowing configuration at an instance level has lead to a bit of confusion/divide as to where exactly the server configuration is. Consolidate all server configuration to a Ruleset. For example, a host configuration would end up looking like this instead:
```yml
  - name: eu1-1
    hostname: "[EU] Swishcast Central"
    ruleset: swishcast_central
    relay_channel: 1238569871910895626
```
This visually only removes two lines (maxplayers and mapcycle) but the maxplayers and mapcycle is often influenced by the ruleset of the server (i.e. rinstagib servers usually only having 12 maxplayers and a curated mapcycle).
